stages:
  - test
  - build
  - release

variables:
  REPO_SERVER_HOST: ${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}

static analyse:
  image: registry.git.jeyserver.com/jalno/phpstan:master
  stage: test
  variables:
    GIT_ROOT_PATH: $CI_BUILDS_DIR/$CI_PROJECT_PATH
  before_script:
    - cd $GIT_ROOT_PATH/packages
    - rm -rf PhpParser && git clone --depth 1 ${REPO_SERVER_HOST}/yeganemehr/PhpParser.git
  script:
    - phpstan analyse -c $GIT_ROOT_PATH/packages/base/phpstan.neon $GIT_ROOT_PATH
