<?php

/**
 * INITAL CLASS MAP OF FRAMEWORK AUTOLOADER. 
 * ALL CLASS NAMES SOULD BE IN lowercase AND FQCN FORMAT.
 * FILES PATH WILL NOT CHECK AND IF THEY NOT EXISTS AN FATAL ERROR WILL OCCUR.
 * 
 * EDIT CAREFULLY!!!
 */
return array(
	'packages\base\autoloadcontainertrait' => __DIR__ . '/libraries/autoloader/AutoloadContainerTrait.php',
	'packages\base\cache' => __DIR__ . '/libraries/cache/Cache.php',
	'packages\base\cache\dbcachehandler' => __DIR__ . '/libraries/cache/DbCachehandler.php',
	'packages\base\cache\filecachehandler' => __DIR__ . '/libraries/cache/FileCachehandler.php',
	'packages\base\cache\filelocktimeoutexception' => __DIR__ . '/libraries/cache/FileLockTimeoutException.php',
	'packages\base\cache\icachehandler' => __DIR__ . '/libraries/cache/ICachehandler.php',
	'packages\base\cache\memcacheextensionexception' => __DIR__ . '/libraries/cache/MemcacheExtensionException.php',
	'packages\base\cache\memcachehandler' => __DIR__ . '/libraries/cache/MemcacheHandler.php',
	'packages\base\cli' => __DIR__ . '/libraries/background/cli.php',
	'packages\base\databaseconfigexception' => __DIR__ . '/libraries/loader/exceptions.php',
	'packages\base\date' => __DIR__ . '/libraries/date/Date.php',
	'packages\base\date\calendarnotexist' => __DIR__ . '/libraries/date/exceptions.php',
	'packages\base\date\date_interface' => __DIR__ . '/libraries/date/date_interface.php',
	'packages\base\date\gregorian' => __DIR__ . '/libraries/date/gregorian.php',
	'packages\base\date\hdate' => __DIR__ . '/libraries/date/hdate.php',
	'packages\base\date\jdate' => __DIR__ . '/libraries/date/jdate.php',
	'packages\base\date\nocalendarexception' => __DIR__ . '/libraries/date/exceptions.php',
	'packages\base\date\timezonenotvalid' => __DIR__ . '/libraries/date/exceptions.php',
	'packages\base\db' => __DIR__ . '/libraries/db/db.php',
	'packages\base\db\dbobject' => __DIR__ . '/libraries/db/dbObject.php',
	'packages\base\db\duplicaterecord' => __DIR__ . '/libraries/db/exceptions.php',
	'packages\base\db\inputdatatype' => __DIR__ . '/libraries/db/exceptions.php',
	'packages\base\db\inputrequired' => __DIR__ . '/libraries/db/exceptions.php',
	'packages\base\db\mysqlidb' => __DIR__ . '/libraries/db/MysqliDb.php',
	'packages\base\db\databaseexception' => __DIR__ . '/libraries/db/DatabaseException.php',
	'packages\base\db\sqlexception' => __DIR__ . '/libraries/db/SqlException.php',
	'packages\base\event' => __DIR__ . '/libraries/events/event.php',
	'packages\base\eventinterface' => __DIR__ . '/libraries/events/EventInterface.php',
	'packages\base\events' => __DIR__ . '/libraries/events/events.php',
	'packages\base\events\listener' => __DIR__ . '/libraries/events/exceptions.php',
	'packages\base\events\packageload' => __DIR__ . '/libraries/events/PackageLoad.php',
	'packages\base\events\packageloaded' => __DIR__ . '/libraries/events/PackageLoaded.php',
	'packages\base\events\packageregistered' => __DIR__ . '/libraries/events/PackageRegistered.php',
	'packages\base\exception' => __DIR__ . '/libraries/utility/exceptions.php',
	'packages\base\frontend\sourceassetexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\sourceassetfileexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\sourceautoloaderfileexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\sourceconfigexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\sourceviewexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\sourceviewfileexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\sourceviewparentexception' => __DIR__ . '/libraries/frontend/exceptions.php',
	'packages\base\frontend\theme' => __DIR__ . '/libraries/frontend/theme.php',
	'packages\base\http' => __DIR__ . '/libraries/http/http.php',
	'packages\base\internalerror' => __DIR__ . '/libraries/utility/exceptions.php',
	'packages\base\io\node' => __DIR__ . '/libraries/io/Node.php',
	'packages\base\io\bindsocketexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\buffer' => __DIR__ . '/libraries/io/buffer.php',
	'packages\base\io\createsocketexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\directory' => __DIR__ . '/libraries/io/directory.php',
	'packages\base\io\directory\ftp' => __DIR__ . '/libraries/io/directory/ftp.php',
	'packages\base\io\directory\local' => __DIR__ . '/libraries/io/directory/local.php',
	'packages\base\io\directory\sftp' => __DIR__ . '/libraries/io/directory/sftp.php',
	'packages\base\io\directory\tmp' => __DIR__ . '/libraries/io/directory/tmp.php',
	'packages\base\io\exception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\file' => __DIR__ . '/libraries/io/File.php',
	'packages\base\io\file\local' => __DIR__ . '/libraries/io/file/Local.php',
	'packages\base\io\istreamablefile' => __DIR__ . '/libraries/io/IStreamableFile.php',
	'packages\base\io\listensocketexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\notfoundexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\rawlistensocketexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\readexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\socket' => __DIR__ . '/libraries/io/Socket.php',
	'packages\base\io\socketexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\io\validator\ivalidator' => __DIR__ . '/libraries/validator/IValidator.php',
	'packages\base\io\writeexception' => __DIR__ . '/libraries/io/exceptions.php',
	'packages\base\json\jsonexception' => __DIR__ . '/libraries/json/JsonException.php',
	'packages\base\languagecontainertrait' => __DIR__ . '/libraries/translator/LanguageContainerTrait.php',
	'packages\base\listenercontainertrait' => __DIR__ . '/libraries/events/ListenerContainerTrait.php',
	'packages\base\log' => __DIR__ . '/libraries/logging/Log.php',
	'packages\base\log\instance' => __DIR__ . '/libraries/logging/instance.php',
	'packages\base\notfound' => __DIR__ . '/libraries/utility/exceptions.php',
	'packages\base\options' => __DIR__ . '/libraries/config/options.php',
	'packages\base\package' => __DIR__ . '/libraries/loader/Package.php',
	'packages\base\packageautoloaderfileexception' => __DIR__ . '/libraries/loader/exceptions.php',
	'packages\base\packageconfigexception' => __DIR__ . '/libraries/loader/exceptions.php',
	'packages\base\packagenotconfiged' => __DIR__ . '/libraries/loader/exceptions.php',
	'packages\base\packagepermission' => __DIR__ . '/libraries/loader/exceptions.php',
	'packages\base\packages' => __DIR__ . '/libraries/loader/packages.php',
	'packages\base\response' => __DIR__ . '/libraries/utility/Response.php',
	'packages\base\router' => __DIR__ . '/libraries/router/router.php',
	'packages\base\router\controllerexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\domainexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\invalidregexexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\notfound' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\permissionexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\routerruleexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\routerrulepart' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\rule' => __DIR__ . '/libraries/router/rule.php',
	'packages\base\router\rulemiddlewareexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\rulepartnameexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\rulepartvalue' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\router\schemeexception' => __DIR__ . '/libraries/router/exceptions.php',
	'packages\base\storage' => __DIR__ . '/libraries/storage/Storage.php',
	'packages\base\storage\localstorage' => __DIR__ . '/libraries/storage/Storage/LocalStorage.php',
	'packages\base\storage\accessforbiddenexception' => __DIR__ . '/libraries/storage/Storage/AccessForbiddenException.php',
	'packages\base\translator' => __DIR__ . '/libraries/translator/translator.php',
	'packages\base\translator\invalidjson' => __DIR__ . '/libraries/translator/exceptions.php',
	'packages\base\translator\invalidlangcode' => __DIR__ . '/libraries/translator/exceptions.php',
	'packages\base\translator\langalreadyexists' => __DIR__ . '/libraries/translator/exceptions.php',
	'packages\base\translator\language' => __DIR__ . '/libraries/translator/language.php',
	'packages\base\translator\phrasealreadyexists' => __DIR__ . '/libraries/translator/exceptions.php',
);
